<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\GroupTarget;

class GroupTargetSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'group_name' => 'Bayi (0-6 bulan)',
                'age_min' => 0,
                'age_max' => 0,
                'water' => 750,
                'energy' => 440,
                'protein' => 9,
                'fat' => 27,
                'carbohydrates' => 60,
                'fiber' => 0,
                'ash' => 0,
                'calcium' => 200,
                'phosphorus' => 110,
                'iron' => 0,
                'sodium' => 0,
                'potassium' => 0,
                'copper' => 0,
                'zinc' => 0,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 0,
            ],
            [
                'group_name' => 'Bayi (7-12 bulan)',
                'age_min' => 7,
                'age_max' => 12,
                'water' => 900,
                'energy' => 620,
                'protein' => 13,
                'fat' => 30,
                'carbohydrates' => 95,
                'fiber' => 0,
                'ash' => 0,
                'calcium' => 200,
                'phosphorus' => 275,
                'iron' => 10,
                'sodium' => 0,
                'potassium' => 0,
                'copper' => 0,
                'zinc' => 0,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 15,
            ],
            [
                'group_name' => 'Anak-Anak (1-3 tahun)',
                'age_min' => 1,
                'age_max' => 3,
                'water' => 1000,
                'energy' => 1100,
                'protein' => 27,
                'fat' => 40,
                'carbohydrates' => 130,
                'fiber' => 5,
                'ash' => 1000,
                'calcium' => 400,
                'phosphorus' => 400,
                'iron' => 10,
                'sodium' => 500,
                'potassium' => 800,
                'copper' => 0,
                'zinc' => 5,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 20,
            ],
            [
                'group_name' => 'Anak-Anak (4-6 tahun)',
                'age_min' => 4,
                'age_max' => 6,
                'water' => 1200,
                'energy' => 1400,
                'protein' => 35,
                'fat' => 45,
                'carbohydrates' => 200,
                'fiber' => 10,
                'ash' => 1200,
                'calcium' => 500,
                'phosphorus' => 500,
                'iron' => 12,
                'sodium' => 600,
                'potassium' => 1000,
                'copper' => 0,
                'zinc' => 7,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 25,
            ],
            [
                'group_name' => 'Anak-Anak (7-9 tahun)',
                'age_min' => 7,
                'age_max' => 9,
                'water' => 1400,
                'energy' => 1600,
                'protein' => 45,
                'fat' => 55,
                'carbohydrates' => 230,
                'fiber' => 15,
                'ash' => 1400,
                'calcium' => 600,
                'phosphorus' => 600,
                'iron' => 15,
                'sodium' => 700,
                'potassium' => 1200,
                'copper' => 0,
                'zinc' => 8,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 30,
            ],
            [
                'group_name' => 'Anak-Anak (10-12 tahun)',
                'age_min' => 10,
                'age_max' => 12,
                'water' => 1600,
                'energy' => 1900,
                'protein' => 55,
                'fat' => 65,
                'carbohydrates' => 270,
                'fiber' => 20,
                'ash' => 1600,
                'calcium' => 700,
                'phosphorus' => 700,
                'iron' => 18,
                'sodium' => 800,
                'potassium' => 1500,
                'copper' => 0,
                'zinc' => 10,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 35,
            ],
            [
                'group_name' => 'Anak-Anak (13-15 tahun)',
                'age_min' => 13,
                'age_max' => 15,
                'water' => 1800,
                'energy' => 2200,
                'protein' => 65,
                'fat' => 75,
                'carbohydrates' => 300,
                'fiber' => 25,
                'ash' => 1800,
                'calcium' => 800,
                'phosphorus' => 800,
                'iron' => 20,
                'sodium' => 900,
                'potassium' => 1800,
                'copper' => 0,
                'zinc' => 12,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 40,
            ],
            [
                'group_name' => 'Remaja (16-18 tahun)',
                'age_min' => 16,
                'age_max' => 18,
                'water' => 2000,
                'energy' => 2500,
                'protein' => 75,
                'fat' => 85,
                'carbohydrates' => 350,
                'fiber' => 30,
                'ash' => 2000,
                'calcium' => 900,
                'phosphorus' => 900,
                'iron' => 25,
                'sodium' => 1000,
                'potassium' => 2000,
                'copper' => 0,
                'zinc' => 15,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 45,
            ],
            [
                'group_name' => 'Dewasa (19-29 tahun)',
                'age_min' => 19,
                'age_max' => 29,
                'water' => 2000,
                'energy' => 2400,
                'protein' => 65,
                'fat' => 70,
                'carbohydrates' => 350,
                'fiber' => 30,
                'ash' => 2000,
                'calcium' => 1000,
                'phosphorus' => 1000,
                'iron' => 15,
                'sodium' => 1500,
                'potassium' => 2000,
                'copper' => 0,
                'zinc' => 15,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 90,
            ],
            [
                'group_name' => 'Dewasa (30-49 tahun)',
                'age_min' => 30,
                'age_max' => 49,
                'water' => 2000,
                'energy' => 2200,
                'protein' => 65,
                'fat' => 70,
                'carbohydrates' => 350,
                'fiber' => 30,
                'ash' => 2000,
                'calcium' => 1000,
                'phosphorus' => 1000,
                'iron' => 10,
                'sodium' => 1500,
                'potassium' => 2000,
                'copper' => 0,
                'zinc' => 12,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 90,
            ],
            [
                'group_name' => 'Dewasa (50-64 tahun)',
                'age_min' => 50,
                'age_max' => 64,
                'water' => 2000,
                'energy' => 2000,
                'protein' => 65,
                'fat' => 65,
                'carbohydrates' => 300,
                'fiber' => 30,
                'ash' => 2000,
                'calcium' => 1000,
                'phosphorus' => 800,
                'iron' => 10,
                'sodium' => 1500,
                'potassium' => 2000,
                'copper' => 0,
                'zinc' => 10,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 90,
            ],
            [
                'group_name' => 'Lansia (65+ tahun)',
                'age_min' => 65,
                'age_max' => null,
                'water' => 2000,
                'energy' => 1800,
                'protein' => 65,
                'fat' => 60,
                'carbohydrates' => 250,
                'fiber' => 30,
                'ash' => 2000,
                'calcium' => 1000,
                'phosphorus' => 800,
                'iron' => 10,
                'sodium' => 1300,
                'potassium' => 2000,
                'copper' => 0,
                'zinc' => 8,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 90,
            ],
            [
                'group_name' => 'Wanita Hamil',
                'age_min' => null,
                'age_max' => null,
                'water' => 2300,
                'energy' => 2500,
                'protein' => 75,
                'fat' => 70,
                'carbohydrates' => 350,
                'fiber' => 35,
                'ash' => 2300,
                'calcium' => 1000,
                'phosphorus' => 1000,
                'iron' => 25,
                'sodium' => 1500,
                'potassium' => 2500,
                'copper' => 0,
                'zinc' => 15,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 95,
            ],
            [
                'group_name' => 'Wanita Menyusui',
                'age_min' => null,
                'age_max' => null,
                'water' => 2600,
                'energy' => 2800,
                'protein' => 85,
                'fat' => 80,
                'carbohydrates' => 350,
                'fiber' => 35,
                'ash' => 2600,
                'calcium' => 1000,
                'phosphorus' => 1000,
                'iron' => 20,
                'sodium' => 1500,
                'potassium' => 2500,
                'copper' => 0,
                'zinc' => 12,
                'retinol' => 0,
                'beta_carotene' => 0,
                'total_carotene' => 0,
                'thiamin' => 0,
                'riboflavin' => 0,
                'niacin' => 0,
                'vitamin_c' => 100,
            ],
        ];

        GroupTarget::insert($data);
        $this->command->info("GroupTarget seeding completed successfully!");
    }
}